version: "3.8"

services:
  gateway:
    image: nginx:stable
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - service1
      - frontend

  service1:
    build: ./service1
    container_name: blog-backend
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=blogdb
    networks:
      - app-network
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - app-network

  db:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: blog-frontend
    networks:
      - app-network

volumes:
  redis-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
